### ISSUE TITLE
这里统计一下 可用/不可用 的设备类型和型号

### ISSUE THREAD

**Issue by XiaoMiku01** [XiaoMiku01/hass-hjq#3]
可用网络摄像头
华为G51MI-1
岭雁摄像头LYC40-PTZ-1

**Comment by fenglou777** [comment]
c31 没有设备

**Comment by Tanboyboy** [comment]
cm3y 摄像头 tplink代工 博联sp5f-cna 都无法 发现

**Comment by XiaoMiku01** [comment]
感谢测试 目前原因是获取设备列表接口返回空导致的 正在解决中

**Comment by Tanboyboy** [comment]
能支持和家亲的 哪些设备 摄像头 排插 ？？？
摄像头能不能 存储在sd卡上回放



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月24日(周四) 下午2:07
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [XiaoMiku01/hass-hjq] 这里统计一下 可用/不可用 的设备类型和型号 (Issue #3)




 
感谢测试 目前原因是获取设备列表接口返回空导致的 正在解决中

**Comment by mkopl545** [comment]
和家望 HDC-51和小白CMSXJB都无法 发现

**Comment by XiaoMiku01** [comment]
重新抓包发现 并不是所有的设备都走通用接口 很大一部分都是不同的接口 需要巨大的工作挖掘 耐心等待

**Comment by XiaoMiku01** [comment]
> 和家望 HDC-51和小白CMSXJB都无法 发现

我测了我刚买的 和家望 HDC-51 可以用

**Comment by cvip313** [comment]
cmcc-v2，可以登录，没有实体。

**Comment by Tanboyboy** [comment]
cm3y 无实体



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月28日(周一) 晚上9:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [XiaoMiku01/hass-hjq] 这里统计一下 可用/不可用 的设备类型和型号 (Issue #3)




 
cmcc-v2，可以登录，没有实体。

**Comment by cvip313** [comment]
实测LYC40-PTZ不行，没有实体。

**Comment by Magic-riding** [comment]
新华三(h3c)TC2101 无实体

**Comment by sirchinj** [comment]
cmcc-v2，可以登录，没有实体。

**Comment by yz-repository** [comment]
可用的：
CMCC-V8B/CMCC-V7A

不可用的：
CM3Y/C15/CM3TPA

**Comment by sirchinj** [comment]
EverVV
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "XiaoMiku01/hass-hjq"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月15日(星期五) 下午4:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [XiaoMiku01/hass-hjq] 这里统计一下 可用/不可用 的设备类型和型号 (Issue #3)





 
可用的：
 CMCC-V8B/CMCC-V7A
 
不可用的：
 CM3Y/C15/CM3TPA/CMCC-V2

**Comment by Tianci8888** [comment]
P30 无实体

**Comment by pan8664716** [comment]
Blurams 摄像头 U30 不可用

**Comment by pan8664716** [comment]
> Blurams 摄像头 U30 不可用

日志如下：
`
日志记录器: homeassistant.components.camera
来源: helpers/entity_platform.py:364
集成: 摄像头 (文档, 问题)
首次出现: 00:48:51 (3 次总计出现)
上次记录: 01:05:34

Error while setting up hass_hjq platform for camera
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/hass_hjq/camera.py", line 32, in async_setup_entry
    for camera in cameras:
TypeError: 'NoneType' object is not iterable
`

**Comment by binghun9806** [comment]
> 可用网络摄像头 华为G51MI-1 岭雁摄像头LYC40-PTZ-1

亲测岭雁摄像头LYC40-PTZ 无实体

**Comment by xuanguang** [comment]
**和家亲 中兴摄像头 ZXHN K745** 测试可用 :)
简单易用，完全按照说明安装即可。

---- 是可以添加，首页能看到实时图像，点击打开播放有白板，不知道是不是因为没有装TF卡，按说应该显示直播。后续再测试

**Comment by sqqs1234** [comment]
爱飞田cmsxj47h 摄像头 显示没有设备或实体

**Comment by sqqs1234** [comment]
移动cmcc-v4a 没有设备或实体

**Comment by Tanboyboy** [comment]
感觉这个项目是不是已经废了，这么久了，没有更新，摄像头 实体还是没有？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2025年3月25日(周二) 上午8:35
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [XiaoMiku01/hass-hjq] 这里统计一下 可用/不可用 的设备类型和型号 (Issue #3)


   
爱飞田cmsxj47h 摄像头 显示没有设备或实体

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;
  sqqs1234 left a comment (XiaoMiku01/hass-hjq#3)
 
爱飞田cmsxj47h 摄像头 显示没有设备或实体
